apiVersion: apps/v1
kind: Deployment
metadata:
  name: s2i-dotnetcore-ex-deployment
spec:
  selector:
    matchLabels:
      app: s2i-dotnetcore-ex
  template:
    metadata:
      labels:
        app: s2i-dotnetcore-ex
    spec:
      containers:
        - name: s2i-dotnetcore-ex
          image: piomin/s2i-dotnetcore-ex
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: s2i-dotnetcore-ex-service
spec:
  type: ClusterIP
  selector:
    app: s2i-dotnetcore-ex
  ports:
    - port: 8080
